### ISSUE TITLE
请问支持quarkus3.15吗？

### ISSUE THREAD

**Issue by tzxylao** [flynndi/quarkus-jimmer-extension#507]

**Comment by flynndi** [comment]
Quarkus 3.15 has been supported since [0.0.1.CR38](https://github.com/flynndi/quarkus-jimmer-extension/releases/tag/0.0.1.CR38)

**Comment by tzxylao** [comment]
我有遇到个情况通过这样解决的
<img width="900" alt="image" src="https://github.com/user-attachments/assets/7280932d-aa6f-47a6-8a84-5c88b6704ead" />
我的配置如下
<img width="366" alt="image" src="https://github.com/user-attachments/assets/2127d269-2118-4845-afbb-d3f5d704045c" />
因为找不到seata配置走默认的方言报错， 如果能兼容这种情况最好 @flynndi

**Comment by flynndi** [comment]
@tzxylao 

try [0.0.1.CR42](https://github.com/flynndi/quarkus-jimmer-extension/releases/tag/0.0.1.CR42)  


I have noticed this issue and have updated the way dialects are configured in the new version  
Now you can configure dialects as shown in the figure    

![3d7b7a3754217dd2ac7c8a87e462ad57](https://github.com/user-attachments/assets/d61dbc87-2c35-4265-96e0-f4da65f76640)
