### ISSUE TITLE
没有设置默认的ObjectMapper

### ISSUE THREAD

**Issue by tzxylao** [flynndi/quarkus-jimmer-extension#510]
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/e89e3b28-0db5-40d1-9e23-58817f9a72c2" />
麻烦加下这块代码，用自己创建的objectMapper来序列化

**Comment by flynndi** [comment]
@babyfish-ct   Whether need to initialize sqlClient DefaultSerializedTypeObjectMapper in extension     

@tzxylao  This is a universal solution     
![ba40f79dc2d9dbba908ddd506bd966aa](https://github.com/user-attachments/assets/6e1947fe-10c6-4584-84d8-d436876a0488)

**Comment by flynndi** [comment]
Jimmer's author says no
